# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Category:
  fields:
    list: name
    form: name
  order_by: 
  relationships: members
  filters: 
  search: name
  application: nshvll

Member:
  fields:
    list: name, email, url, active
    form: name, email, url
    options:
      booleans:
        active: ['Yes', 'No']
  order_by: 
  relationships: categories
  filters: 
  search: name
  application: nshvll

